// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://roxuycokvzupgkdheaxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJveHV5Y29rdnp1cGdrZGhlYXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Mzc3NTksImV4cCI6MjA2NTExMzc1OX0.tGumqMQYQQOo5zbH4soc3pVNuu-MsTs-Ep0lnLmLqcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);